services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]

  anki-production:
    build: .
    command: bash -c "rm -f tmp/pidsserver.pid && bundle exec rails s -b '0.0.0.0'"
    volumes:
      - .:/rails
    ports:
     - 3000:3000
    depends_on:
      db:
       condition: service_healthy

volumes:
  pgdata:

networks:
  default:
    name: applications-network
